### ISSUE TITLE
Commands without "Does this launch an app" hang

### ISSUE THREAD

**Issue by RedHatter** [Tormak9970/bash-shortcuts#18] opened 2023-06-06 01:15 UTC
When a command has "Does this launch an app" checked it works fine without it check the command just hangs.

**Comment by Tormak9970** [comment] 2023-06-06 14:53
This is part of a group of issues caused by a recent steam update. Haven't had a chance to address them

**Comment by Tormak9970** [comment] 2023-06-12 20:04
Closing as this has been fixed. Will release an update once additional issues are also fixed

**Closed by Tormak9970** 2023-06-12 20:04 UTC
